# Generated by Django 4.2.1 on 2023-05-28 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='assigned_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engineer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='number',
            field=models.IntegerField(default=1685282840750499800),
        ),
    ]
