# Generated by Django 4.2.1 on 2023-05-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='number',
            field=models.IntegerField(default=1685448108073013700),
        ),
    ]
