# Generated by Django 4.2.1 on 2023-06-01 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0002_incident_state_alter_incident_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='number',
            field=models.IntegerField(default=1685608651676694600),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/inc_attachments/')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incident.incident')),
            ],
        ),
    ]
