# Generated by Django 4.2.1 on 2023-06-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0003_alter_incident_number_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='extension',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='number',
            field=models.IntegerField(default=1685719386173538300),
        ),
    ]
