# Generated by Django 4.2.1 on 2023-05-29 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incident', '0003_alter_incident_number_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='number',
            field=models.IntegerField(default=1685374582224311500),
        ),
    ]
