# Generated by Django 4.2.1 on 2023-06-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0004_attachment_extension_attachment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='extension',
            field=models.TextField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='incident',
            name='number',
            field=models.IntegerField(default=1685719446007380200),
        ),
    ]
