# Generated by Django 4.2.1 on 2023-05-29 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0004_group_name_group_owner_alter_group_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='assignment_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='incident.group'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='number',
            field=models.IntegerField(default=1685375694718911800),
        ),
    ]
