# Generated by Django 4.2.1 on 2023-05-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0006_alter_incident_number_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='number',
            field=models.IntegerField(default=1685376890506381200),
        ),
    ]
