# Generated by Django 4.2.1 on 2023-06-08 08:51

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0006_alter_attachment_extension_alter_incident_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='incident',
            name='number',
            field=models.IntegerField(default=time.time_ns),
        ),
        migrations.AddField(
            model_name='incident',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, to='incident.tag'),
        ),
    ]
