# Generated by Django 4.2.1 on 2023-06-08 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0007_tag_alter_incident_number_incident_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=12)),
                ('extension', models.CharField(blank=True, max_length=12)),
                ('file', models.FileField(upload_to='files/knowledge_files/')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incident.tag')),
            ],
        ),
    ]
