# Generated by Django 4.2.1 on 2023-06-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0010_alter_knowledgefiles_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='knowledge',
            field=models.BooleanField(default=False),
        ),
    ]
