# Generated by Django 4.2.1 on 2023-06-10 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0012_remove_knowledgefiles_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.incident')),
                ('knowledge_files', models.ManyToManyField(blank=True, default=None, to='incident.knowledgefiles')),
            ],
        ),
    ]
