# Generated by Django 4.2.1 on 2023-06-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0013_knowledgearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticle',
            name='name',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
