# Generated by Django 4.2.1 on 2023-06-10 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0014_knowledgearticle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgearticle',
            name='incident',
        ),
    ]
