# Generated by Django 4.2.1 on 2023-06-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0015_remove_knowledgearticle_incident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgefiles',
            name='category',
        ),
        migrations.RemoveField(
            model_name='knowledgefiles',
            name='tag',
        ),
    ]
