# Generated by Django 4.2.1 on 2023-06-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0016_remove_knowledgefiles_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='knowledge_article',
            field=models.ManyToManyField(blank=True, default=None, to='incident.knowledgearticle'),
        ),
    ]
